image: ubuntu:20.04

before_script:
  - apt-get update  -yqq
  - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
  - apt-get install -yqq openjdk-17-jdk-headless
  - apt-get install -yqq gpg
  - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - mkdir -p /root/.gnupg
  - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
  - apt-get update  -yqq
  - apt-get install -yqq sbt

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy -Dsbt.ci=true"

cache:
  untracked: true
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"

stages:
  - checkFormatting
  - test
  - build
#  - deploy-dev

checkFormatting:
  stage: checkFormatting
  script:
    - 'sbt scalafmtSbtCheck scalafmtCheckAll'

test:
  stage: test
  script:
    - apt-get install -yqq npm
    - npm install @openapitools/openapi-generator-cli -g
    - 'sbt clean generateCode coverage test multi-jvm:test coverageReport'

build:
  services:
    - docker:19.03.12-dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script: |
    apt-get install -yqq curl
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -yqq
    apt-get install -yqq docker-ce-cli
    apt-get install -yqq npm
    npm install @openapitools/openapi-generator-cli -g
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    sbt clean generateCode compile k8tyGitlabCIPublish docker:publish
    echo VERSION=$(sbt -Dsbt.log.noformat=true 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ') >> vars.env
    echo COMMIT=`git log -1 --pretty=%B | head -n 1 | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z` >> vars.env
    cat vars.env
  artifacts:
    reports:
      dotenv: vars.env
  only:
    - master

#Deploy Dev:
#  image: dtzar/helm-kubectl
#  stage: deploy-dev
#  environment: development
#  before_script:
#    - helm plugin install https://github.com/jkroepke/helm-secrets --version v3.11.0
#    - apk add --no-cache vault libcap && setcap cap_ipc_lock= /usr/sbin/vault
#  script:
#    - echo ${VERSION}
#    - echo ${COMMIT}
#    - cd k8s
#    - chmod +x deploy.sh
#    - ./deploy.sh
#  needs:
#    - build
#  tags:
#    - development-env
#  only:
#    - master
#