object Versions {
  lazy val akkaVersion              = "2.6.19"
  lazy val akkaHttpVersion          = "10.2.9"
  lazy val akkaHttpJsonVersion      = "1.39.2"
  lazy val akkaManagementVersion    = "1.1.3"
  lazy val scalaGraphVersion        = "1.13.4"
  lazy val retryVersion             = "0.3.4"
  lazy val h2Version                = "2.1.210"
  lazy val postgresqlVersion        = "42.3.3"
  lazy val scalikeJDBCVersion       = "4.0.0"
  lazy val flywayVersion            = "8.5.4"
  lazy val circeVersion             = "0.14.1"
  lazy val json4sVersion            = "4.0.4"
  lazy val mustacheVersion          = "0.9.10"
  lazy val openapi4jVersion         = "1.0.7"
  lazy val jacksonVersion           = "2.13.1"
  lazy val commonsFileUploadVersion = "1.4"
  lazy val scalaLogging             = "3.9.4"
  lazy val logbackVersion           = "1.2.11"
  lazy val scalatestVersion         = "3.2.11"
}
