apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: witboost-addons-es
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: witboost-addons-secrets
  dataFrom:
    - extract:
        key: snowflake