apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "snowflake"
          valueMap:
            SNOWFLAKE_USER: ADMIN
            SNOWFLAKE_PASSWORD: PASSWORD
            SNOWFLAKE_ROLE: ACCOUNTADMIN
            SNOWFLAKE_ACCOUNT: TC
            SNOWFLAKE_WAREHOUSE: QA
            JDBC_URL: jdbc:snowflake://TC-QA.snowflakecomputing.com
            SNOWFLAKE_ACCOUNT_LOCATOR_URL: https://tg.eu-west-1.snowflakecomputing.com
            SNOWFLAKE_PRINCIPALS_MAPPER_STRATEGY: identity
            # The below three variables are required only if the mapper strategy is table-based instead of identity-based one.
            SNOWFLAKE_PRINCIPALS_MAPPER_TABLE_BASED_DATABASE: WITBOOST
            SNOWFLAKE_PRINCIPALS_MAPPER_TABLE_BASED_SCHEMA: CONFIGURATIONS
            SNOWFLAKE_PRINCIPALS_MAPPER_TABLE_BASED_TABLE: PRINCIPALS_MAPPING
            # Tags
            SNOWFLAKE_TAG_REFERENCES_DATABASE: WITBOOST
            SNOWFLAKE_TAG_REFERENCES_SCHEMA: CONFIGURATIONS
            SNOWFLAKE_TAG_REFERENCES_VIEW: TAG_REFERENCES2