apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
