CREATE DATABASE IF NOT EXISTS WITBOOST;

CREATE SCHEMA IF NOT EXISTS WITBOOST.CONFIGURATIONS;

CREATE TABLE IF NOT EXISTS WITBOOST.CONFIGURATIONS.PRINCIPALS_MAPPING (
  WITBOOST_IDENTITY TEXT NOT NULL,
  SNOWFLAKE_IDENTITY TEXT NOT NULL,
  LAST_UPDATE TIMESTAMP DEFAULT current_timestamp(),
  PRIMARY KEY (WITBOOST_IDENTITY)
);